dreampsy2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('dreams.urls', namespace="dreams")),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social'))
]

dreams/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', index, name="inicio"),
    url(r'^agradable$', agradable, name="agradable"),
    url(r'^chat$', chat, name="chat"),
    url(r'^desagradable$', desagradable, name="desagradable"),
    url(r'^instruccion$', instruccion, name="instruccion"),
    url(r'^introduccion$', introduccion,
        name="introduccion"),
    url(r'^introducciones$', introducciones,
        name="introducciones"),
    url(r'^personaje-agradables$', personaje_agradable,
        name="personaje_agradable"),
    url(r'^personaje-desagradables$', personaje_desagradable,
        name="personaje_desagradable"),
    url(r'^cambio-lenguaje/$', cambio_lenguaje, name='cambio_lenguaje'),
    url(r'^crear-sueño/$', crear_sueño, name="crear_sueño"),
    url(r'^crear-descripcion/$', crear_descripcion, name="crear_descrip"),
    url(r'^crear-personajes/$', crear_personajes, name="crear_personaje"),
    url(r'^mis-suenos/$', mis_suenos, name="mis_suenos"),


]

dreams/models.py
import json
from django.db import models
from django.db.models.signals import post_save
from django.core import serializers
from django.dispatch import receiver
from users.models import UserProfile
# Create your models here.


class Dream(models.Model):
    agradable = models.BooleanField(default=True)
    userprofile = models.ForeignKey(UserProfile)
    descripcion = models.TextField(max_length=300, blank=True)

    personaje1 = models.CharField(max_length=40, blank=True)
    personaje2 = models.CharField(max_length=40, blank=True)

    def __str__(self):
        return str(self.userprofile)

class MenuIdioma(models.Model):
    idioma = models.CharField(max_length=30)
    activo = models.BooleanField(default=False)
    def __str__(self):
        return self.idioma

class Idioma(models.Model):
    lenguaje = models.ForeignKey(MenuIdioma, related_name="idioma_traductor")
    #pantalla 1

    sub_pregunta = models.CharField(max_length=30)
    sad_image = models.CharField(max_length=30)
    happy_image = models.CharField(max_length=30)

    btn_continuar = models.CharField(max_length=30)
    btn_cancelar = models.CharField(max_length=30)
    btn_confirmar = models.CharField(max_length=30)
    sad_mensaje = models.TextField(max_length=200)
    happy_mensaje = models.TextField(max_length=200)
    ayuda1 = models.TextField(max_length=200)

    def __str__(self):
        return str(self.lenguaje)


@receiver(post_save, sender=Idioma)
def post_save_idioma(sender, instance, **kwargs):
    print(instance.__dict__)
    name = str(instance.__dict__['_lenguaje_cache'])
    extension = '.json'
    nombre_archivo = name+extension
    print(name+extension)

    hola = instance.__dict__['_state']
    instance.__dict__.pop('_state')
    instance.__dict__.pop('_lenguaje_cache')
    print(instance.__dict__)
    with open(nombre_archivo, "w") as out:
        #data = serializers.serialize("json", instance.__dict__)
        #out.write(data)
        data = json.dumps(instance.__dict__)
        out.write(data)
    instance.__dict__['_state'] = hola

users/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


class UserProfile(User):
    avatar = models.URLField(default='', blank=True)
    slug = models.SlugField()

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.slug = slugify(self.username)
        super(UserProfile, self).save(force_insert, force_update, using,
                                      update_fields)

    @property
    def get_absolute_url(self):
        return reverse('auth_login')

    class Meta:
        app_label = 'users'

dreams/views.py
import json
from django.shortcuts import render, HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Idioma, Dream

@login_required
def index(request):
    datos = json.loads(open('ENGLISH.json').read())
    datos['idiomas'] = Idioma.objects.all()
    print(datos)
    return render(request, 'dreams/describir(inicio).html', datos)


def agradable(request):
    return render(request, 'dreams/agradable.html', {})


def chat(request):
    return render(request, 'dreams/chat.html', {})


def desagradable(request):
    return render(request, 'dreams/desagradable.html', {})


def describir(request):
    return render(request, 'dreams/describir(inicio).html', {})


def instruccion(request):
    return render(request, 'dreams/instruccion.html', {})


def introduccion(request):
    return render(request, 'dreams/introduccion.html', {})


def introducciones(request):
    return render(request, 'dreams/introducciones.html', {})


def personaje_agradable(request):
    return render(request, 'dreams/personajes-agradable.html', {})


def personaje_desagradable(request):
    return render(request, 'dreams/personajes-desagradable.html', {})


def cambio_lenguaje(request):
    if request.is_ajax():
        idioma = request.GET['idioma']
        extension = '.json'
        nombre_archivo = idioma + extension
        datos = json.loads(open(nombre_archivo).read())
        response = json.dumps(datos)

        return HttpResponse(response, content_type='application/json')

def crear_sueño(request):
    if request.is_ajax():
        user = request.user.userprofile.id
        estado = request.GET['estado_sueño']

        if estado == "1":
            dream = Dream(userprofile_id=user)
            dream.save()
            print(dream.id)
        else:
            dream = Dream(agradable=False, userprofile_id=user)
            dream.save()
            print(dream.id);
        return HttpResponse(dream.id)


def crear_descripcion(request):
    if request.is_ajax():
        user = request.user.userprofile.id
        id = int(request.GET['id_sueno'])
        texto = request.GET['texto']
        dream = Dream.objects.get(id=id)
        dream.descripcion = texto
        dream.save()

        return HttpResponse("positivo")


def crear_personajes(request):
    if request.is_ajax():
        user = request.user.userprofile.id
        id = int(request.GET['id_sueno'])
        personaje1 = request.GET['personaje1']
        personaje2 = request.GET['personaje2']
        dream = Dream.objects.get(id=id)
        dream.personaje1 = personaje1
        dream.personaje2 = personaje2
        dream.save()
        return HttpResponse("positivo")


def mis_suenos(request):
    user = request.user.userprofile.id
    dreams = Dream.objects.filter(userprofile_id=user)

    return render(request, 'dreams/mis_sueños.html', {'dreams': dreams})

users/views.py
from django.shortcuts import render

# Create your views here.

templates/dreams/agradable.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Documento sin título</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<link href="https://fonts.googleapis.com/css?family=Montserrat:500,600,700|Shadows+Into+Light+Two" rel="stylesheet">
<link href="{% static  'css/font-awesome.css'%}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>

<body>
	<div id="menu">
    	<i class=" menu fa fa-bars" aria-hidden="true"></i>
        <div class="logo"><img src="{% static 'images/logo-dreamspy.png' %}" /></div>
        <div class="ayuda"><i class="fa fa-question-circle" aria-hidden="true"></i></div>
    </div>
    <div id="container">
        <div class="agradable"><div class="spacer"></div><img src=" {% static 'images/happy.png' %}" /><div class="es-title">¿Qué fue lo <span class="tit-shadow underlined">Agradable</span> del sueño?</div><div class="spacer"></div></div>
        <div class="desescribir"><textarea class="renglones" placeholder="Lo agradable del sueño fue..."></textarea><div class="centered"><a class="bot boton">Continuar</a></div><div class="spacer"></div></div>
    </div>
    <div id="footer"></div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src=" {% static 'js/code.js' %}"></script>
<script src=" {% static 'js/main.js' %}"></script>
</html>

templates/dreams/chat.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Chat - Dreampsy</title>
<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">

<link href="https://fonts.googleapis.com/css?family=Montserrat:500,600,700|Shadows+Into+Light+Two" rel="stylesheet">
<link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="{% static 'js/code.js' %}"></script>

</head>

<body>
	<div id="menu">
    	<i class=" menu fa fa-bars" aria-hidden="true"></i>
        <div class="logo"><img src="{% static 'images/logo-dreamspy.png' %}" /></div>
        <div class="ayuda"><i class="fa fa-question-circle" aria-hidden="true"></i></div>
    </div>
    <div id="container" class="chat-page">
    	<div class="chats" id="chats">
        	<span>sadadsdsa</span>
        	<span>sadadsdsa</span>
        	<span>sadadsdsa</span>
        </div>
        
        <div class="caja_chat">
        	<div class="swicher"><i class="fa fa-circle" aria-hidden="true"></i><div class="tooltip"><i class="fa fa-caret-down" aria-hidden="true"></i>Personaje 1</div></div>
        	<textarea class="chat" placeholder="Esbríbele a Mar"></textarea>
       	 	<div id="sender"></div>
        </div>
        <!--<div class="centered none"><a class="bot" href="personajes-agradable.html">Continuar</a></div>-->
    </div>
    <div id="footer"></div>
</body>
</html>

templates/dreams/desagradable.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Documento sin título</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<link href="https://fonts.googleapis.com/css?family=Montserrat:500,600,700|Shadows+Into+Light+Two" rel="stylesheet">
<link href="{% static  'css/font-awesome.css'%}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>

<body>
	<div id="menu">
    	<i class=" menu fa fa-bars" aria-hidden="true"></i>
        <div class="logo"><img src="{% static 'images/logo-dreamspy.png' %}" /></div>
        <div class="ayuda"><i class="fa fa-question-circle" aria-hidden="true"></i></div>
    </div>
    <div id="container">
        <div class="desagradable"><div class="spacer"></div><img src="{% static 'images/sad.png' %}" /><div class="es-title">¿Qué fue lo <span class="tit-shadow underlined">Desagradable</span> del sueño?</div><div class="spacer"></div></div>
        <div class="desescribir"><textarea class="renglones" placeholder="Lo desagradable del sueño fue..."></textarea><div class="centered"><a class="bot boton">Continuar</a></div><div class="spacer"></div></div>
        
    </div>
    <div id="footer"></div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src=" {% static 'js/main.js' %}"></script>
</body>
</html>

templates/dreams/describir(inicio).html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Escoger DreamPsy</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<link href="https://fonts.googleapis.com/css?family=Montserrat:500,600,700|Shadows+Into+Light+Two" rel="stylesheet">
<link href="{% static  'css/font-awesome.css'%}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link href="{% static 'css/rangeslider.css' %} " rel="stylesheet">

</head>

<body>
	<div id="menu">
    	<i class=" menu fa fa-bars" aria-hidden="true"></i>
        <div class="logo"><img src="{% static 'images/logo-dreamspy.png' %}" /></div>
        <div class="ayuda" style="opacity:0;"><i class="fa fa-question-circle" aria-hidden="true"></i></div>
    </div>
    <div id="container">
    	<div class="sure desagradable tit-shadow centered f20 white"><div class="spacer"></div><img src="{% static 'images/sad.png' %}" />{{ sad_mensaje }}<a class="bot negativo continue">{{ btn_confirmar }}</a><br /><a class="cancelar">{{ btn_cancelar }}</a></div>
        
        
        <div class="sure agradable tit-shadow centered f20 white"><div class="spacer"></div><img src="{% static 'images/happy.png' %}" />{{ happy_mensaje }}<a class="bot negativo continue">{{ btn_confirmar }}</a><br /><a class="cancelar">{{ btn_cancelar }}</a></div>
    	<h3>hola {{ user.username }}</h3>
    <a href="{% url 'logout' %}">Cerrar sesion</a>
        {% for idioma in idiomas %}
    	    <ul>
                <li><a href="#" class="idioma">{{ idioma }}</a></li>
            </ul>
    	{% endfor %}
        <a href="{% url 'dreams:mis_suenos' %}">Mis sueños</a>
    	<div class="title">{{ sub_pregunta }}</div>
		
        <ul class="opciones">
            <li class="desagradable"><img src="{% static 'images/sad.png' %}" /><span id="sad_image">{{ sad_image }}</span><a href="{% url 'dreams:desagradable' %}"></a></li>
        	<li class="agradable"><img src=" {% static 'images/happy.png' %}" /><span id="happy_image">{{ happy_image }}</span><a href="{% url 'dreams:agradable' %}"></a></li>
        </ul><div class="spacer"></div>
        <div id="range"></div>
        <div class="clear"></div>
        <div class="centered"><a class="bot wait disabled">{{ btn_continuar }}</a></div>
    	<div class="spacer"></div>
    </div>
    <div id="footer"></div>
    <div class="foo-help slideDown s5"><i class="fa fa-angle-down" aria-hidden="true"></i><span>{{ ayuda1 }}</span></div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src=" {% static 'js/code.js' %}"></script>
<script src="{% static 'js/rangeslider.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script>
	linked='continuando---->';
	new RangeSlider($("#range"), {
		size: 2,
		borderSize: 0.1,
		percentage: 50,
		onMove: function(event) { berificaStado(); },
		onUp: function(event) { berificaStado(); }
	});
</script>
</html>

templates/dreams/instruccion.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Introduccion</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<link href="https://fonts.googleapis.com/css?family=Montserrat:500,600,700|Shadows+Into+Light+Two" rel="stylesheet">
<link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/glide.core.css' %}">
<link rel="stylesheet" href="{% static 'css/glide.theme.css' %}">
<!-- Demo stylesheet -->
<link rel="stylesheet" href="{% static 'css/demo.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="{% static 'js/code.js' %}"></script>

</head>

<body>
	<div id="menu">
    	<i class=" menu fa fa-bars" aria-hidden="true"></i>
        <div class="logo"><img src="{% static 'images/logo-dreamspy.png' %}" /></div>
        <div class="ayuda"><i class="fa fa-question-circle" aria-hidden="true"></i></div>
    </div>
    <div id="container">
    	<div class="module module--horizontal">
			<div id="Slideshow" class="glide">
				<div class="glide__arrows">
					<button class="glide__arrow next bot negativo" data-glide-dir=">">Siguiente</button>
				</div>
				

				<div class="glide__wrapper">
					<ul class="glide__track">
						<li class="glide__slide">
							<div class="box" style="background-color: #8538EA;">
                            	Los sueños son una rápida vía de acceso a nuestro mundo interior. Los elementos y personajes presentes en ellos son aspectos de nuestra personalidad representados por nuestra "Psiquis" mediante un lenguaje simbólico.
                            </div>
						</li>
						<li class="glide__slide">
							<div class="box" style="background-color: #8538EA;">
                            	<span>Para alcanzar la plenitud es importante comenzar por hacer consciencia de  formas de ser, actuar o de sentir propias que se manifiestan a modo de <span class="text-verde underlined">proyecciones*</span> en nuestros sueños. 
                                <span class="text-verde contextual tit-shadow">*Mecanismo mediante el cual le atribuimos aspectos propios a otros.</span></span>
                            </div>
						</li>
						<li class="glide__slide">
							<div class="box" style="background-color: #8538EA;">
                            	Vamos a empezar - Cierra tus Ojos
                           	</div>
						</li>
					</ul>
				</div>

				<div class="glide__bullets"></div>

			</div>
		</div>
        <div class="centered"><a class="bot negativo over-bot" href="{% url 'dreams:chat' %}">Continuar</a></div>
    	
        
        
    </div>
    <div id="footer"></div>
    <script src="{% static 'js/jquery.js' %}"></script>
		<script src="{% static 'js/glide.js' %}"></script>
		<script>
			

			var carousel = $('#Carousel').glide({
				type: 'carousel',
				startAt: 1,
				touchDistance: 2
			});

			var slider = $('#Slider').glide({
				type: 'slider',
				startAt: 2
			});

			var slideshow = $('#Slideshow').glide({
				type: 'slideshow',
				startAt: 1,
				autoplay:false,
        		afterTransition: function(event) { berificaEnd(); },
				swipeEnd: function(event) { alert('ola'); }
				
				
			});
			function berificaEnd(){
				
				if( $('.glide__slide:last').hasClass('active') ){
					$('.glide__arrows').addClass('active');
					$('.over-bot').addClass('active');
				}
			}
			

		</script>
</body>
</html>

templates/dreams/introduccion.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Introduccion</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<link href="https://fonts.googleapis.com/css?family=Montserrat:500,600,700|Shadows+Into+Light+Two" rel="stylesheet">
<link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/glide.core.css' %}">
<link rel="stylesheet" href="{% static 'css/glide.theme.css' %}">
<!-- Demo stylesheet -->
<link rel="stylesheet" href="{% static 'css/demo.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="{% static 'js/code.js' %}"></script>

</head>

<body>
	<div id="menu">
    	<i class=" menu fa fa-bars" aria-hidden="true"></i>
        <div class="logo"><img src="{% static 'images/logo-dreamspy.png' %}" /></div>
        <div class="ayuda"><i class="fa fa-question-circle" aria-hidden="true"></i></div>
    </div>
    <div id="container">
    	<div class="module module--horizontal">
			<div id="Slideshow" class="glide">
				<!--<div class="glide__arrows">
					<button class="glide__arrow next bot negativo" data-glide-dir=">">Siguiente</button>
				</div>-->
				

				<div class="glide__wrapper">
					<ul class="glide__track">
						<li class="glide__slide">
							<div class="box" style="background-color: #8538EA;">
                            	Los sueños son una rápida vía de acceso a nuestro mundo interior. Los elementos y personajes presentes en ellos son aspectos de nuestra personalidad representados por nuestra "Psiquis" mediante un lenguaje simbólico.
                            </div>
						</li>
						<li class="glide__slide">
							<div class="box" style="background-color: #8538EA;">
                            	<span>Para alcanzar la plenitud es importante comenzar por hacer consciencia de  formas de ser, actuar o de sentir propias que se manifiestan a modo de <span class="text-verde underlined">proyecciones*</span> en nuestros sueños. 
                                <span class="text-verde contextual tit-shadow">*Mecanismo mediante el cual le atribuimos aspectos propios a otros.</span></span>
                            </div>
						</li>
					</ul>
				</div>

				<div class="glide__bullets"></div>

			</div>
		</div>
        <div class="centered"><a class="bot negativo over-bot" href="{% url 'dreams:instruccion' %}">Continuar</a></div>
    	
        
        
    </div>
    <div id="footer"></div>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/glide.js' %}"></script>
		<script>
			

			var carousel = $('#Carousel').glide({
				type: 'carousel',
				startAt: 1,
				touchDistance: 2
			});

			var slider = $('#Slider').glide({
				type: 'slider',
				startAt: 2
			});

			var slideshow = $('#Slideshow').glide({
				type: 'slideshow',
				startAt: 1,
        		afterTransition: function(event) { berificaEnd(); }
				
				
			});
			function berificaEnd(){
				
				if( $('.glide__slide:last').hasClass('active') ){
					$('.glide__arrows').addClass('active');
					$('.over-bot').addClass('active');
				}
			}
			

		</script>
</body>
</html>

templates/dreams/introducciones.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Introduccion</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<link href="https://fonts.googleapis.com/css?family=Montserrat:500,600,700|Shadows+Into+Light+Two" rel="stylesheet">
<link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/glide.core.css' %}">
<link rel="stylesheet" href="{% static 'css/glide.theme.css' %}">
<!-- Demo stylesheet -->
<link rel="stylesheet" href="{% static 'css/demo.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="{% static 'js/code.js' %}"></script>

</head>

<body>
	<div id="menu">
    	<i class=" menu fa fa-bars" aria-hidden="true"></i>
        <div class="logo"><img src="{% static 'images/logo-dreamspy.png' %}" /></div>
        <div class="ayuda"><i class="fa fa-question-circle" aria-hidden="true"></i></div>
    </div>
    <div id="container">
				<!--<div class="glide__arrows">
					<button class="glide__arrow next bot negativo" data-glide-dir=">">Siguiente</button>
				</div>-->
				
				
        	<div id="text_star_wars" class="star-wars desagradable centered f20 white">
				<br /><br /><br /><br />
                Los sueños son una rápida vía de acceso a nuestro mundo interior. Los elementos y personajes presentes en ellos son aspectos de nuestra personalidad representados por nuestra "Psiquis" mediante un lenguaje simbólico, a modo de proyecciones*.<br /><br />


P1  y  P2 son en realidad facetas tuyas; lo que experimentan, lo que sienten y la forma en la que los consideras evidencian la relación que tienes contigo mism@.<br /><br />


Para alcanzar la plenitud es importante comenzar por hacer consciencia de estas formas de ser, actuar y/o de sentir manifestadas en tus sueños.<br /><br />
 <div class="tit-shadow text-verde f30">*Mecanismo mediante el cual le atribuimos aspectos propios a otros</div>

				<br /><br /><br /><br />
        		<div class="centered"><a class="bot negativo " href="{% url 'dreams:instruccion' %}">Continuar</a></div>
        		
		</div>
    	
        
        
    </div>
    <div id="footer"></div>
    <script>
		$("#text_star_wars").animate({ scrollTop: $(document).height()+1000 }, 35000);
		console.log($(document).height(), ' $(document).height()')
	</script>
		
</body>
</html>

templates/dreams/mis_sueños.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for dream in dreams %}
        -----------------------------------------
        {% if dream.agradable %}
            <p>Sueño agradable</p>
        {% else %}
            <p>Sueño desagradable</p>
        {% endif %}
        <p>Descripcion del sueño:</p>
        {{ dream.descripcion }}
        <p>Personaje1: {{ dream.personaje1 }}</p>
        <p>Personaje1: {{ dream.personaje2 }}</p>
    {% endfor %}

</body>
</html>